In [1]:
import torch
import numpy as np

In [3]:
rubicks = torch.ones(128,3,3,3)
print(rubicks)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        ...,


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 

## Creating a tensor

In [4]:
x =torch.rand(3,2)
y = torch.zeros(2,2)
z = torch.ones_like(y)
print(x)
print(y)
print(z)

tensor([[0.4282, 0.6897],
        [0.0976, 0.8223],
        [0.1896, 0.7244]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


## Autograd

In [5]:
x = torch.ones(2,2,requires_grad=True)
#perform tensor operations
y = x+2
z = y*y*3
out = z.mean()

#compute gradients
out.backward()

#print gradients
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### Modules

In [7]:
import torch.nn as nn

# define a neural network module

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(10,5)
        self.fc2 = nn.Linear(5,1)

    def forward(self,x):
        x = self.fc1(x)
        x = nn.functional.relu(x)
        x = self.fc2(x)
        return x
# create an instance of the module
net = Net()
#pass input through the module
input = torch.randn(1,10)
out = net(input)

## Optimizers

In [8]:
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(10,5)
        self.fc2 = nn.Linear(5,1)

    def forward(self,x):
        x = self.fc1(x)
        x = nn.functional.relu(x)
        x = self.fc2(x)
        return x
    
net = Net()

optimizer = optim.SGD(net.parameters(),lr=0.01)

#compute gradients
input = torch.randn(1,10)
out = net(input)
loss = out.sum()
loss.backward()
optimizer.step()

### Data loading

In [9]:
import torch.utils.data as data

# Define a custom dataset
class MyDataset(data.Dataset):
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        x = self.data[index][0]
        y = self.data[index][1]
        return x, y

    def __len__(self):
        return len(self.data)

# Create an instance of the dataset
mydata = MyDataset([(torch.randn(3), torch.randn(1)) for i in range(10)])

# Create a data loader
loader = data.DataLoader(mydata, batch_size=2, shuffle=True)

# Iterate over the data loader
for batch in loader:
    x, y = batch
    print(x.shape, y.shape)

torch.Size([2, 3]) torch.Size([2, 1])
torch.Size([2, 3]) torch.Size([2, 1])
torch.Size([2, 3]) torch.Size([2, 1])
torch.Size([2, 3]) torch.Size([2, 1])
torch.Size([2, 3]) torch.Size([2, 1])
